[phases.setup]
nixPkgs = ['nodejs', 'python39', 'yarn']

[phases.install]
cmds = [
    'cd frontend && yarn install',
    'cd backend && pip install -r requirements.txt'
]

[phases.build]
cmds = ['cd frontend && yarn build']

[start]
cmd = 'cd backend && python -m uvicorn server:app --host 0.0.0.0 --port $PORT'
